name: cm_example
description: Demonstrates how to use the cm plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  cm: ^0.0.4
#  cm:
#    path: ../

flutter:


  uses-material-design: true


