name: cm
description: Cm plugin project.
version: 0.0.4
author: dai<daihang1229@163.com>
homepage: https://github.com/daihang1229
publish_to: https://pub.dartlang.org


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  plugin:
    androidPackage: im.weshine.plugin.cm
    pluginClass: CmPlugin

