name: cm
description: Cm plugin project.
version: 0.0.1
author: dai
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  plugin:
    androidPackage: im.weshine.plugin.cm
    pluginClass: CmPlugin

